@startuml
!include <C4/C4.puml>
!include <C4/C4_Deployment.puml>


Person(engineer, "Инженер", "DevOps-инженер, настраивающий платформу")
System(System_IoT, "Device Service", "Микросервисная IoT-платформа")
System_Ext(device, "IoT-устройство", "Внешний датчик или контроллер, отправляет данные")
System_Ext(grafana, "Grafana", "Мониторинг и дашборды")

Rel(engineer, System_IoT, "Мониторинг платформы", "HTTP/REST, UI")
Rel(device, System_IoT, "Телеметрия и команды", "MQTT/HTTP")
Rel(engineer, grafana, "Просмотр метрик и логов", "HTTP (dashboards)")
Rel(System_IoT, grafana, "Экспорт метрик и логов", "Prometheus, Loki")

@enduml