// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: router-manager-service.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_PENDING Status = 0
	Status_SENT    Status = 1
	Status_ACKED   Status = 2
	Status_FAILED  Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "PENDING",
		1: "SENT",
		2: "ACKED",
		3: "FAILED",
	}
	Status_value = map[string]int32{
		"PENDING": 0,
		"SENT":    1,
		"ACKED":   2,
		"FAILED":  3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_router_manager_service_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_router_manager_service_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_router_manager_service_proto_rawDescGZIP(), []int{0}
}

type CommandType int32

const (
	CommandType_REBOOT CommandType = 0
	CommandType_PING   CommandType = 1
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "REBOOT",
		1: "PING",
	}
	CommandType_value = map[string]int32{
		"REBOOT": 0,
		"PING":   1,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_router_manager_service_proto_enumTypes[1].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_router_manager_service_proto_enumTypes[1]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_router_manager_service_proto_rawDescGZIP(), []int{1}
}

type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouterId      string                 `protobuf:"bytes,1,opt,name=router_id,json=routerId,proto3" json:"router_id,omitempty"`
	CommandType   CommandType            `protobuf:"varint,2,opt,name=command_type,json=commandType,proto3,enum=api.v1.CommandType" json:"command_type,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_router_manager_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_manager_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_router_manager_service_proto_rawDescGZIP(), []int{0}
}

func (x *CommandRequest) GetRouterId() string {
	if x != nil {
		return x.RouterId
	}
	return ""
}

func (x *CommandRequest) GetCommandType() CommandType {
	if x != nil {
		return x.CommandType
	}
	return CommandType_REBOOT
}

func (x *CommandRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type PollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouterId      string                 `protobuf:"bytes,1,opt,name=router_id,json=routerId,proto3" json:"router_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollRequest) Reset() {
	*x = PollRequest{}
	mi := &file_router_manager_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRequest) ProtoMessage() {}

func (x *PollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_manager_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollRequest.ProtoReflect.Descriptor instead.
func (*PollRequest) Descriptor() ([]byte, []int) {
	return file_router_manager_service_proto_rawDescGZIP(), []int{1}
}

func (x *PollRequest) GetRouterId() string {
	if x != nil {
		return x.RouterId
	}
	return ""
}

type PollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*Command             `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollResponse) Reset() {
	*x = PollResponse{}
	mi := &file_router_manager_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollResponse) ProtoMessage() {}

func (x *PollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_manager_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollResponse.ProtoReflect.Descriptor instead.
func (*PollResponse) Descriptor() ([]byte, []int) {
	return file_router_manager_service_proto_rawDescGZIP(), []int{2}
}

func (x *PollResponse) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RouterId      string                 `protobuf:"bytes,2,opt,name=router_id,json=routerId,proto3" json:"router_id,omitempty"`
	CommandType   CommandType            `protobuf:"varint,3,opt,name=command_type,json=commandType,proto3,enum=api.v1.CommandType" json:"command_type,omitempty"`
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Status        Status                 `protobuf:"varint,5,opt,name=status,proto3,enum=api.v1.Status" json:"status,omitempty"`
	SentAt        string                 `protobuf:"bytes,6,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	AckedAt       string                 `protobuf:"bytes,7,opt,name=acked_at,json=ackedAt,proto3" json:"acked_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_router_manager_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_router_manager_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_router_manager_service_proto_rawDescGZIP(), []int{3}
}

func (x *Command) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Command) GetRouterId() string {
	if x != nil {
		return x.RouterId
	}
	return ""
}

func (x *Command) GetCommandType() CommandType {
	if x != nil {
		return x.CommandType
	}
	return CommandType_REBOOT
}

func (x *Command) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Command) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_PENDING
}

func (x *Command) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

func (x *Command) GetAckedAt() string {
	if x != nil {
		return x.AckedAt
	}
	return ""
}

func (x *Command) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type AckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouterId      string                 `protobuf:"bytes,1,opt,name=router_id,json=routerId,proto3" json:"router_id,omitempty"`
	CommandId     string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_router_manager_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_manager_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_router_manager_service_proto_rawDescGZIP(), []int{4}
}

func (x *AckRequest) GetRouterId() string {
	if x != nil {
		return x.RouterId
	}
	return ""
}

func (x *AckRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

var File_router_manager_service_proto protoreflect.FileDescriptor

const file_router_manager_service_proto_rawDesc = "" +
	"\n" +
	"\x1crouter-manager-service.proto\x12\x06api.v1\x1a\x1bgoogle/protobuf/empty.proto\"\x7f\n" +
	"\x0eCommandRequest\x12\x1b\n" +
	"\trouter_id\x18\x01 \x01(\tR\brouterId\x126\n" +
	"\fcommand_type\x18\x02 \x01(\x0e2\x13.api.v1.CommandTypeR\vcommandType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"*\n" +
	"\vPollRequest\x12\x1b\n" +
	"\trouter_id\x18\x01 \x01(\tR\brouterId\";\n" +
	"\fPollResponse\x12+\n" +
	"\bcommands\x18\x01 \x03(\v2\x0f.api.v1.CommandR\bcommands\"\x83\x02\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\trouter_id\x18\x02 \x01(\tR\brouterId\x126\n" +
	"\fcommand_type\x18\x03 \x01(\x0e2\x13.api.v1.CommandTypeR\vcommandType\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\x12&\n" +
	"\x06status\x18\x05 \x01(\x0e2\x0e.api.v1.StatusR\x06status\x12\x17\n" +
	"\asent_at\x18\x06 \x01(\tR\x06sentAt\x12\x19\n" +
	"\backed_at\x18\a \x01(\tR\aackedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"H\n" +
	"\n" +
	"AckRequest\x12\x1b\n" +
	"\trouter_id\x18\x01 \x01(\tR\brouterId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId*6\n" +
	"\x06Status\x12\v\n" +
	"\aPENDING\x10\x00\x12\b\n" +
	"\x04SENT\x10\x01\x12\t\n" +
	"\x05ACKED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03*#\n" +
	"\vCommandType\x12\n" +
	"\n" +
	"\x06REBOOT\x10\x00\x12\b\n" +
	"\x04PING\x10\x012\xbb\x01\n" +
	"\x0eCommandService\x12?\n" +
	"\vsendCommand\x12\x16.api.v1.CommandRequest\x1a\x16.google.protobuf.Empty\"\x00\x123\n" +
	"\x04poll\x12\x13.api.v1.PollRequest\x1a\x14.api.v1.PollResponse\"\x00\x123\n" +
	"\x03ack\x12\x12.api.v1.AckRequest\x1a\x16.google.protobuf.Empty\"\x00B\x17Z\x15internal/proto/api/v1b\x06proto3"

var (
	file_router_manager_service_proto_rawDescOnce sync.Once
	file_router_manager_service_proto_rawDescData []byte
)

func file_router_manager_service_proto_rawDescGZIP() []byte {
	file_router_manager_service_proto_rawDescOnce.Do(func() {
		file_router_manager_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_router_manager_service_proto_rawDesc), len(file_router_manager_service_proto_rawDesc)))
	})
	return file_router_manager_service_proto_rawDescData
}

var file_router_manager_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_router_manager_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_router_manager_service_proto_goTypes = []any{
	(Status)(0),            // 0: api.v1.Status
	(CommandType)(0),       // 1: api.v1.CommandType
	(*CommandRequest)(nil), // 2: api.v1.CommandRequest
	(*PollRequest)(nil),    // 3: api.v1.PollRequest
	(*PollResponse)(nil),   // 4: api.v1.PollResponse
	(*Command)(nil),        // 5: api.v1.Command
	(*AckRequest)(nil),     // 6: api.v1.AckRequest
	(*emptypb.Empty)(nil),  // 7: google.protobuf.Empty
}
var file_router_manager_service_proto_depIdxs = []int32{
	1, // 0: api.v1.CommandRequest.command_type:type_name -> api.v1.CommandType
	5, // 1: api.v1.PollResponse.commands:type_name -> api.v1.Command
	1, // 2: api.v1.Command.command_type:type_name -> api.v1.CommandType
	0, // 3: api.v1.Command.status:type_name -> api.v1.Status
	2, // 4: api.v1.CommandService.sendCommand:input_type -> api.v1.CommandRequest
	3, // 5: api.v1.CommandService.poll:input_type -> api.v1.PollRequest
	6, // 6: api.v1.CommandService.ack:input_type -> api.v1.AckRequest
	7, // 7: api.v1.CommandService.sendCommand:output_type -> google.protobuf.Empty
	4, // 8: api.v1.CommandService.poll:output_type -> api.v1.PollResponse
	7, // 9: api.v1.CommandService.ack:output_type -> google.protobuf.Empty
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_router_manager_service_proto_init() }
func file_router_manager_service_proto_init() {
	if File_router_manager_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_router_manager_service_proto_rawDesc), len(file_router_manager_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_router_manager_service_proto_goTypes,
		DependencyIndexes: file_router_manager_service_proto_depIdxs,
		EnumInfos:         file_router_manager_service_proto_enumTypes,
		MessageInfos:      file_router_manager_service_proto_msgTypes,
	}.Build()
	File_router_manager_service_proto = out.File
	file_router_manager_service_proto_goTypes = nil
	file_router_manager_service_proto_depIdxs = nil
}
