@startuml

actor User
participant "API Orchestrator" as AO
participant "event-service" as ES
participant "device-service" as DS
participant "router-manager" as RM

User -> AO : POST /api/v1/devices/{id}/version {targetVersion}
== Шаг A: Отправка события ==
AO -> ES : POST /events/{deviceId}/version {targetVersion, status=UPDATING}
ES --> AO : 200 {eventId}
== Шаг B: фиксация версии ==
AO -> DS : PATCH /devices/{id}/version {targetVersion, status=UPDATING}
DS --> AO : 200 {prevVersion, etag}
== Шаг C: отправка команды ==
AO -> RM : sendUpdateVersion(deviceId, targetVersion)
alt success
  RM --> AO : {commandId}
  AO --> User : 200 {prevVersion, targetVersion, commandId}
else failure
  RM --> AO : 5xx / timeout
  AO -> DS : POST /devices/{id}/version/rollback {rollbackTo=prevVersion, status=FAIL}
  DS --> AO : 200
  AO --> User : 502 {error:"ROUTER_MANAGER_FAILED", compensated:true}

  DS --> AO : 5xx / timeout
  AO -> ES : POST /events/{id}/version/rollback {rollbackTo=prevVersion, status=FAIL}
    DS --> AO : 200
    AO --> User : 502 {error:"DEVICE_SERVICE_FAILED", compensated:true}

end
@enduml